const T = (name, o) => ({ name, land: true, move: 1, defence: 1, capture: 1, fertility: 0, build: true, water: null, ...o });

export const TERRAIN = [
  T("deep_ocean", { land: false, build: false, water: "deep" }),
  T("ocean", { land: false, build: false, water: "open" }),
  T("shallows", { land: false, build: false, water: "shallow" }),
  T("lake", { land: false, build: false, water: "shallow" }),
  T("river", { move: 2.5, defence: 1.4, capture: 1.2, fertility: 1.3, build: false }),
  T("coral_reef", { land: false, build: false, water: "shallow" }),
  T("beach", { move: 1.1, capture: 0.8, fertility: 0.2 }),
  T("desert", { move: 1.4, capture: 0.6, fertility: 0.05 }),
  T("dunes", { move: 1.8, defence: 1.1, capture: 0.7, fertility: 0, build: false }),
  T("salt_flat", { move: 1.1, capture: 0.5, fertility: 0 }),
  T("dry_earth", { move: 1.1, capture: 0.8, fertility: 0.3 }),
  T("savanna", { capture: 0.9, fertility: 0.6 }),
  T("steppe", { capture: 0.9, fertility: 0.7 }),
  T("grassland", { fertility: 1.0 }),
  T("plains", { fertility: 1.1 }),
  T("meadow", { fertility: 1.0 }),
  T("scrub", { move: 1.2, fertility: 0.4 }),
  T("forest", { move: 1.6, defence: 1.3, capture: 1.3, fertility: 0.3, forest: true }),
  T("pine_forest", { move: 1.7, defence: 1.3, capture: 1.3, fertility: 0.2, forest: true }),
  T("jungle", { move: 2.4, defence: 1.5, capture: 1.6, fertility: 0.4, forest: true }),
  T("swamp", { move: 2.8, defence: 1.2, capture: 1.5, fertility: 0.2, build: false }),
  T("marsh", { move: 2.2, defence: 1.1, capture: 1.3, fertility: 0.5 }),
  T("mangrove", { move: 2.6, defence: 1.3, capture: 1.5, fertility: 0.2, build: false }),
  T("hills", { move: 1.8, defence: 1.5, capture: 1.4, fertility: 0.5 }),
  T("highlands", { move: 2.0, defence: 1.6, capture: 1.5, fertility: 0.4 }),
  T("mountain", { move: 3.5, defence: 2.2, capture: 2.2, fertility: 0.05, build: false }),
  T("high_mountain", { move: 5, defence: 2.6, capture: 3, fertility: 0, build: false }),
  T("snow_peak", { move: 8, defence: 3, capture: 4, fertility: 0, build: false }),
  T("cliff", { move: Infinity, defence: 3, capture: 5, fertility: 0, build: false }),
  T("volcano", { move: 6, defence: 2, capture: 3, fertility: 0, build: false }),
  T("lava", { land: true, move: Infinity, capture: Infinity, build: false }),
  T("tundra", { move: 1.4, capture: 0.8, fertility: 0.15 }),
  T("snow", { move: 2.0, capture: 1.0, fertility: 0 }),
  T("glacier", { move: 4, capture: 2.5, fertility: 0, build: false }),
  T("sea_ice", { land: false, build: false, water: "ice" }),
  T("farmland", { fertility: 1.4 }),
  T("cleared", { fertility: 0.8 }),
  T("scorched", { move: 1.2, fertility: 0 }),
  T("crater", { move: 2.5, capture: 1.2, fertility: 0, build: false }),
  T("rubble", { move: 1.8, defence: 1.3, fertility: 0 }),
  T("urban", { move: 0.9, defence: 1.6, capture: 1.2, fertility: 0 }),
  T("badlands", { move: 2.2, defence: 1.4, capture: 1.3, fertility: 0.05 }),
  T("canyon", { move: 4, defence: 2, capture: 2, fertility: 0.05, build: false }),
  T("escarpment", { move: 3.2, defence: 2, capture: 1.8, fertility: 0.1, build: false }),
  T("bog", { move: 3.2, defence: 1.1, capture: 1.4, fertility: 0.3, build: false }),
  T("thicket", { move: 2.4, defence: 1.5, capture: 1.5, fertility: 0.3, forest: true }),
  T("bamboo", { move: 2.2, defence: 1.5, capture: 1.4, fertility: 0.5, forest: true }),
  T("rocky_desert", { move: 1.8, defence: 1.2, capture: 0.9, fertility: 0.05 }),
  T("boulders", { move: 2.6, defence: 1.7, capture: 1.6, fertility: 0.05, build: false }),
  T("scree", { move: 2.8, defence: 1.3, capture: 1.6, fertility: 0, build: false }),
  T("ice_field", { move: 3, defence: 1.1, capture: 1.4, fertility: 0, build: false }),
  T("mudflat", { move: 2.2, defence: 1, capture: 1.1, fertility: 0.2, build: false }),
  T("highland_pass", { move: 1.6, defence: 1.8, capture: 1.6, fertility: 0.2 }),
];

export const TID = Object.fromEntries(TERRAIN.map((t, i) => [t.name, i]));
export const isLand = id => TERRAIN[id].land && TERRAIN[id].move < Infinity;
export const isWater = id => !TERRAIN[id].land;
